version: '3.8'

services:
  db:
    restart: always
    image: "postgres:12.3-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - rengine_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: always
    image: docker.pkg.github.com/yogeshojha/rengine/rengine:latest
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - rengine_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "celery -A reNgine worker -l INFO"
    volumes:
      - .:/app
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
    networks:
      - rengine_network

  redis:
    image: redis:alpine
    hostname: redis
    networks:
      - rengine_network

  celery-beat:
    build: .
    command: celery -A reNgine beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DEBUG=1
    depends_on:
      - redis
    networks:
      - rengine_network
    volumes:
      - .:/app

networks:
  rengine_network:
volumes:
  postgres_data:
  gf_patterns:
  nuclei_templates:
