name: reNgine CI test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
        matrix:
            runs-on: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.runs-on}}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rengine:$(date +%s)
