name: reNgine CI test 

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build:

    runs-on: ubuntu-latest, macos-latest, windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reNgine:$(date +%s)
