name: reNgine CI test

on:
  push:
    branches: [ master, stable ]
  pull_request:
    branches: [ master, stable ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rengine:$(date +%s)
