name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Yayy! Thanks for creating your first issue! We hope that you keep contributing to reNgine'
        pr-message: 'Yayy! Thanks for creating your first PR! We hope that you keep contributing to reNgine'
